### ISSUE TITLE
Error on initial migration

### ISSUE THREAD

**Issue by pau1m** [wyvernprotocol/wyvern-v3#21]
Error: CompileError: /Users/x/Documents/webs/wyvern-v3/contracts/exchange/Exchange.sol:77:27: CompilerError: Stack too deep, try removing local variables.
            Order(address(uints[0]), address(uints[1]), address(ui ...
                          ^---^

Compilation failed. See above.
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/index.js:103:1)
Truffle v5.0.29 (core: 5.0.29)
Node v10.16.0

**Comment by cwgoes** [comment]
Thanks; fixed.
