### ISSUE TITLE
Windows/GIT : fatal: unable to checkout working tree 

### ISSUE THREAD

**Issue by SMLaursen** [wyvernprotocol/wyvern-v3#63]
When trying to clone the repository on Windows I get :  

> error: invalid path 'test/aux.js'
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.

Supposedly _aux_ is a reserved filename on Windows and should probably be renamed : 
https://stackoverflow.com/a/61616948

**Comment by cwgoes** [comment]
Haha, that's ridiculous. We can change it, do you want to submit a PR?

**Comment by SMLaursen** [comment]
I agree and I submitted a PR renaming it to util.js - feel free to change it ;)
