### ISSUE TITLE
Bug report for StaticMarket.sol

### ISSUE THREAD

**Issue by jackcpku** [wyvernprotocol/wyvern-v3#68]
https://github.com/wyvernprotocol/wyvern-v3/blob/403f866940b4ef304d24c2147bd9503e89e1cec7/contracts/StaticMarket.sol#L136-L156

The return value should not be 1 since multiple ERC20 tokens are transferred. This will cause inconsistency with the meaning of variable `fills`.

**Comment by MarvinJanssen** [comment]
Orders involving an ERC721 cannot be partially filled, hence `1`. Such orders should always have a `maximumFill` of `1`. The `fills` variable corresponds to order fills, not tokens transferred, although both may coincide.

**Comment by jackcpku** [comment]
> Orders involving an ERC721 cannot be partially filled, hence `1`. Such orders should always have a `maximumFill` of `1`. The `fills` variable corresponds to order fills, not tokens transferred, although both may coincide.

https://github.com/wyvernprotocol/wyvern-v3/blob/403f866940b4ef304d24c2147bd9503e89e1cec7/test/7-static-market-matching.js#L617-L622

Ok, so here in line 618, `maximumFill` should not be `buyingPrice`, instead be `1`

**Comment by MarvinJanssen** [comment]
It appears so.
